// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateChatChatsPostData, CreateChatChatsPostErrors, CreateChatChatsPostResponses, CreateMessageMessagesPostData, CreateMessageMessagesPostErrors, CreateMessageMessagesPostResponses, CreatePostPostsPostData, CreatePostPostsPostErrors, CreatePostPostsPostResponses, CreateProfileProfilesPostData, CreateProfileProfilesPostErrors, CreateProfileProfilesPostResponses, DeleteProfileProfilesProfileIdDeleteData, DeleteProfileProfilesProfileIdDeleteErrors, DeleteProfileProfilesProfileIdDeleteResponses, ReadChatChatsChatIdGetData, ReadChatChatsChatIdGetErrors, ReadChatChatsChatIdGetResponses, ReadChatMessagesChatsChatIdMessagesGetData, ReadChatMessagesChatsChatIdMessagesGetErrors, ReadChatMessagesChatsChatIdMessagesGetResponses, ReadChatsChatsGetData, ReadChatsChatsGetErrors, ReadChatsChatsGetResponses, ReadMessagesMessagesGetData, ReadMessagesMessagesGetErrors, ReadMessagesMessagesGetResponses, ReadPostPostsPostIdGetData, ReadPostPostsPostIdGetErrors, ReadPostPostsPostIdGetResponses, ReadPostsPostsGetData, ReadPostsPostsGetErrors, ReadPostsPostsGetResponses, ReadProfilePostsProfilesProfileIdPostsGetData, ReadProfilePostsProfilesProfileIdPostsGetErrors, ReadProfilePostsProfilesProfileIdPostsGetResponses, ReadProfileProfilesProfileIdGetData, ReadProfileProfilesProfileIdGetErrors, ReadProfileProfilesProfileIdGetResponses, ReadProfilesProfilesGetData, ReadProfilesProfilesGetErrors, ReadProfilesProfilesGetResponses, UpdateProfileProfilesProfileIdPatchData, UpdateProfileProfilesProfileIdPatchErrors, UpdateProfileProfilesProfileIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Profiles
 */
export const readProfilesProfilesGet = <ThrowOnError extends boolean = false>(options?: Options<ReadProfilesProfilesGetData, ThrowOnError>) => (options?.client ?? client).get<ReadProfilesProfilesGetResponses, ReadProfilesProfilesGetErrors, ThrowOnError>({ url: '/profiles/', ...options });

/**
 * Create Profile
 */
export const createProfileProfilesPost = <ThrowOnError extends boolean = false>(options: Options<CreateProfileProfilesPostData, ThrowOnError>) => (options.client ?? client).post<CreateProfileProfilesPostResponses, CreateProfileProfilesPostErrors, ThrowOnError>({
    url: '/profiles/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Profile
 */
export const deleteProfileProfilesProfileIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteProfileProfilesProfileIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteProfileProfilesProfileIdDeleteResponses, DeleteProfileProfilesProfileIdDeleteErrors, ThrowOnError>({ url: '/profiles/{profile_id}', ...options });

/**
 * Read Profile
 */
export const readProfileProfilesProfileIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadProfileProfilesProfileIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadProfileProfilesProfileIdGetResponses, ReadProfileProfilesProfileIdGetErrors, ThrowOnError>({ url: '/profiles/{profile_id}', ...options });

/**
 * Update Profile
 */
export const updateProfileProfilesProfileIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateProfileProfilesProfileIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateProfileProfilesProfileIdPatchResponses, UpdateProfileProfilesProfileIdPatchErrors, ThrowOnError>({
    url: '/profiles/{profile_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Posts
 */
export const readPostsPostsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadPostsPostsGetData, ThrowOnError>) => (options?.client ?? client).get<ReadPostsPostsGetResponses, ReadPostsPostsGetErrors, ThrowOnError>({ url: '/posts/', ...options });

/**
 * Create Post
 */
export const createPostPostsPost = <ThrowOnError extends boolean = false>(options: Options<CreatePostPostsPostData, ThrowOnError>) => (options.client ?? client).post<CreatePostPostsPostResponses, CreatePostPostsPostErrors, ThrowOnError>({
    url: '/posts/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Post
 */
export const readPostPostsPostIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadPostPostsPostIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadPostPostsPostIdGetResponses, ReadPostPostsPostIdGetErrors, ThrowOnError>({ url: '/posts/{post_id}', ...options });

/**
 * Read Profile Posts
 */
export const readProfilePostsProfilesProfileIdPostsGet = <ThrowOnError extends boolean = false>(options: Options<ReadProfilePostsProfilesProfileIdPostsGetData, ThrowOnError>) => (options.client ?? client).get<ReadProfilePostsProfilesProfileIdPostsGetResponses, ReadProfilePostsProfilesProfileIdPostsGetErrors, ThrowOnError>({ url: '/profiles/{profile_id}/posts/', ...options });

/**
 * Read Chats
 */
export const readChatsChatsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadChatsChatsGetData, ThrowOnError>) => (options?.client ?? client).get<ReadChatsChatsGetResponses, ReadChatsChatsGetErrors, ThrowOnError>({ url: '/chats/', ...options });

/**
 * Create Chat
 */
export const createChatChatsPost = <ThrowOnError extends boolean = false>(options: Options<CreateChatChatsPostData, ThrowOnError>) => (options.client ?? client).post<CreateChatChatsPostResponses, CreateChatChatsPostErrors, ThrowOnError>({
    url: '/chats/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Chat
 */
export const readChatChatsChatIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadChatChatsChatIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadChatChatsChatIdGetResponses, ReadChatChatsChatIdGetErrors, ThrowOnError>({ url: '/chats/{chat_id}', ...options });

/**
 * Read Messages
 */
export const readMessagesMessagesGet = <ThrowOnError extends boolean = false>(options?: Options<ReadMessagesMessagesGetData, ThrowOnError>) => (options?.client ?? client).get<ReadMessagesMessagesGetResponses, ReadMessagesMessagesGetErrors, ThrowOnError>({ url: '/messages/', ...options });

/**
 * Create Message
 */
export const createMessageMessagesPost = <ThrowOnError extends boolean = false>(options: Options<CreateMessageMessagesPostData, ThrowOnError>) => (options.client ?? client).post<CreateMessageMessagesPostResponses, CreateMessageMessagesPostErrors, ThrowOnError>({
    url: '/messages/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Chat Messages
 */
export const readChatMessagesChatsChatIdMessagesGet = <ThrowOnError extends boolean = false>(options: Options<ReadChatMessagesChatsChatIdMessagesGetData, ThrowOnError>) => (options.client ?? client).get<ReadChatMessagesChatsChatIdMessagesGetResponses, ReadChatMessagesChatsChatIdMessagesGetErrors, ThrowOnError>({ url: '/chats/{chat_id}/messages/', ...options });
