// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_create_post_posts__post
 */
export type BodyCreatePostPostsPost = {
    /**
     * Text
     */
    text?: string | null;
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * ChatCreate
 */
export type ChatCreate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Profile Ids
     */
    profile_ids: Array<string>;
};

/**
 * ChatPublic
 */
export type ChatPublic = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Text
     */
    text: string;
    /**
     * Post Id
     */
    post_id: string;
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * CommentPublic
 */
export type CommentPublic = {
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
    /**
     * Post Id
     */
    post_id: string;
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageCreate
 */
export type MessageCreate = {
    /**
     * Text
     */
    text: string;
    /**
     * Chat Id
     */
    chat_id: string;
    /**
     * Profile Id
     */
    profile_id: string;
};

/**
 * MessagePublic
 */
export type MessagePublic = {
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: string;
};

/**
 * PostPublic
 */
export type PostPublic = {
    /**
     * Text
     */
    text?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Media Urls
     */
    media_urls?: Array<string>;
};

/**
 * ProfileCreate
 */
export type ProfileCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Avatar
     */
    avatar?: string | null;
    /**
     * Posts Count
     */
    posts_count?: number;
    /**
     * Followers Count
     */
    followers_count?: number;
    /**
     * Following Count
     */
    following_count?: number;
};

/**
 * ProfilePublic
 */
export type ProfilePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Avatar
     */
    avatar?: string | null;
    /**
     * Posts Count
     */
    posts_count?: number;
    /**
     * Followers Count
     */
    followers_count?: number;
    /**
     * Following Count
     */
    following_count?: number;
    /**
     * Id
     */
    id: string;
};

/**
 * ProfileUpdate
 */
export type ProfileUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GoogleCallbackAuthCallbackGooglePostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/auth/callback/google';
};

export type GoogleCallbackAuthCallbackGooglePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleCallbackAuthCallbackGooglePostError = GoogleCallbackAuthCallbackGooglePostErrors[keyof GoogleCallbackAuthCallbackGooglePostErrors];

export type GoogleCallbackAuthCallbackGooglePostResponses = {
    /**
     * Response Google Callback Auth Callback Google Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleCallbackAuthCallbackGooglePostResponse = GoogleCallbackAuthCallbackGooglePostResponses[keyof GoogleCallbackAuthCallbackGooglePostResponses];

export type ReadProfilesProfilesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/profiles/';
};

export type ReadProfilesProfilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProfilesProfilesGetError = ReadProfilesProfilesGetErrors[keyof ReadProfilesProfilesGetErrors];

export type ReadProfilesProfilesGetResponses = {
    /**
     * Response Read Profiles Profiles  Get
     *
     * Successful Response
     */
    200: Array<ProfilePublic>;
};

export type ReadProfilesProfilesGetResponse = ReadProfilesProfilesGetResponses[keyof ReadProfilesProfilesGetResponses];

export type CreateProfileProfilesPostData = {
    body: ProfileCreate;
    path?: never;
    query?: never;
    url: '/profiles/';
};

export type CreateProfileProfilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProfileProfilesPostError = CreateProfileProfilesPostErrors[keyof CreateProfileProfilesPostErrors];

export type CreateProfileProfilesPostResponses = {
    /**
     * Successful Response
     */
    200: ProfilePublic;
};

export type CreateProfileProfilesPostResponse = CreateProfileProfilesPostResponses[keyof CreateProfileProfilesPostResponses];

export type DeleteProfileProfilesProfileIdDeleteData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type DeleteProfileProfilesProfileIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProfileProfilesProfileIdDeleteError = DeleteProfileProfilesProfileIdDeleteErrors[keyof DeleteProfileProfilesProfileIdDeleteErrors];

export type DeleteProfileProfilesProfileIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadProfileProfilesProfileIdGetData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type ReadProfileProfilesProfileIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProfileProfilesProfileIdGetError = ReadProfileProfilesProfileIdGetErrors[keyof ReadProfileProfilesProfileIdGetErrors];

export type ReadProfileProfilesProfileIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProfilePublic;
};

export type ReadProfileProfilesProfileIdGetResponse = ReadProfileProfilesProfileIdGetResponses[keyof ReadProfileProfilesProfileIdGetResponses];

export type UpdateProfileProfilesProfileIdPatchData = {
    body: ProfileUpdate;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type UpdateProfileProfilesProfileIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileProfilesProfileIdPatchError = UpdateProfileProfilesProfileIdPatchErrors[keyof UpdateProfileProfilesProfileIdPatchErrors];

export type UpdateProfileProfilesProfileIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProfilePublic;
};

export type UpdateProfileProfilesProfileIdPatchResponse = UpdateProfileProfilesProfileIdPatchResponses[keyof UpdateProfileProfilesProfileIdPatchResponses];

export type ReadUserByNameUsersNameGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/users/{name}';
};

export type ReadUserByNameUsersNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByNameUsersNameGetError = ReadUserByNameUsersNameGetErrors[keyof ReadUserByNameUsersNameGetErrors];

export type ReadUserByNameUsersNameGetResponses = {
    /**
     * Successful Response
     */
    200: ProfilePublic;
};

export type ReadUserByNameUsersNameGetResponse = ReadUserByNameUsersNameGetResponses[keyof ReadUserByNameUsersNameGetResponses];

export type ReadProfilePostsProfilesProfileIdPostsGetData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/profiles/{profile_id}/posts/';
};

export type ReadProfilePostsProfilesProfileIdPostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProfilePostsProfilesProfileIdPostsGetError = ReadProfilePostsProfilesProfileIdPostsGetErrors[keyof ReadProfilePostsProfilesProfileIdPostsGetErrors];

export type ReadProfilePostsProfilesProfileIdPostsGetResponses = {
    /**
     * Response Read Profile Posts Profiles  Profile Id  Posts  Get
     *
     * Successful Response
     */
    200: Array<PostPublic>;
};

export type ReadProfilePostsProfilesProfileIdPostsGetResponse = ReadProfilePostsProfilesProfileIdPostsGetResponses[keyof ReadProfilePostsProfilesProfileIdPostsGetResponses];

export type ReadChatsChatsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/chats/';
};

export type ReadChatsChatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadChatsChatsGetError = ReadChatsChatsGetErrors[keyof ReadChatsChatsGetErrors];

export type ReadChatsChatsGetResponses = {
    /**
     * Response Read Chats Chats  Get
     *
     * Successful Response
     */
    200: Array<ChatPublic>;
};

export type ReadChatsChatsGetResponse = ReadChatsChatsGetResponses[keyof ReadChatsChatsGetResponses];

export type CreateChatChatsPostData = {
    body: ChatCreate;
    path?: never;
    query?: never;
    url: '/chats/';
};

export type CreateChatChatsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChatChatsPostError = CreateChatChatsPostErrors[keyof CreateChatChatsPostErrors];

export type CreateChatChatsPostResponses = {
    /**
     * Successful Response
     */
    200: ChatPublic;
};

export type CreateChatChatsPostResponse = CreateChatChatsPostResponses[keyof CreateChatChatsPostResponses];

export type ReadChatChatsChatIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type ReadChatChatsChatIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadChatChatsChatIdGetError = ReadChatChatsChatIdGetErrors[keyof ReadChatChatsChatIdGetErrors];

export type ReadChatChatsChatIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChatPublic;
};

export type ReadChatChatsChatIdGetResponse = ReadChatChatsChatIdGetResponses[keyof ReadChatChatsChatIdGetResponses];

export type ReadMessagesMessagesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/messages/';
};

export type ReadMessagesMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMessagesMessagesGetError = ReadMessagesMessagesGetErrors[keyof ReadMessagesMessagesGetErrors];

export type ReadMessagesMessagesGetResponses = {
    /**
     * Response Read Messages Messages  Get
     *
     * Successful Response
     */
    200: Array<MessagePublic>;
};

export type ReadMessagesMessagesGetResponse = ReadMessagesMessagesGetResponses[keyof ReadMessagesMessagesGetResponses];

export type CreateMessageMessagesPostData = {
    body: MessageCreate;
    path?: never;
    query?: never;
    url: '/messages/';
};

export type CreateMessageMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMessageMessagesPostError = CreateMessageMessagesPostErrors[keyof CreateMessageMessagesPostErrors];

export type CreateMessageMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: MessagePublic;
};

export type CreateMessageMessagesPostResponse = CreateMessageMessagesPostResponses[keyof CreateMessageMessagesPostResponses];

export type ReadChatMessagesChatsChatIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}/messages/';
};

export type ReadChatMessagesChatsChatIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadChatMessagesChatsChatIdMessagesGetError = ReadChatMessagesChatsChatIdMessagesGetErrors[keyof ReadChatMessagesChatsChatIdMessagesGetErrors];

export type ReadChatMessagesChatsChatIdMessagesGetResponses = {
    /**
     * Response Read Chat Messages Chats  Chat Id  Messages  Get
     *
     * Successful Response
     */
    200: Array<MessagePublic>;
};

export type ReadChatMessagesChatsChatIdMessagesGetResponse = ReadChatMessagesChatsChatIdMessagesGetResponses[keyof ReadChatMessagesChatsChatIdMessagesGetResponses];

export type ReadPostsPostsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/posts/';
};

export type ReadPostsPostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPostsPostsGetError = ReadPostsPostsGetErrors[keyof ReadPostsPostsGetErrors];

export type ReadPostsPostsGetResponses = {
    /**
     * Response Read Posts Posts  Get
     *
     * Successful Response
     */
    200: Array<PostPublic>;
};

export type ReadPostsPostsGetResponse = ReadPostsPostsGetResponses[keyof ReadPostsPostsGetResponses];

export type CreatePostPostsPostData = {
    body: BodyCreatePostPostsPost;
    path?: never;
    query?: never;
    url: '/posts/';
};

export type CreatePostPostsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostPostsPostError = CreatePostPostsPostErrors[keyof CreatePostPostsPostErrors];

export type CreatePostPostsPostResponses = {
    /**
     * Successful Response
     */
    200: PostPublic;
};

export type CreatePostPostsPostResponse = CreatePostPostsPostResponses[keyof CreatePostPostsPostResponses];

export type ReadPostPostsPostIdGetData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type ReadPostPostsPostIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPostPostsPostIdGetError = ReadPostPostsPostIdGetErrors[keyof ReadPostPostsPostIdGetErrors];

export type ReadPostPostsPostIdGetResponses = {
    /**
     * Successful Response
     */
    200: PostPublic;
};

export type ReadPostPostsPostIdGetResponse = ReadPostPostsPostIdGetResponses[keyof ReadPostPostsPostIdGetResponses];

export type CreateCommentCommentsPostData = {
    body: CommentCreate;
    path?: never;
    query?: never;
    url: '/comments/';
};

export type CreateCommentCommentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCommentCommentsPostError = CreateCommentCommentsPostErrors[keyof CreateCommentCommentsPostErrors];

export type CreateCommentCommentsPostResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type CreateCommentCommentsPostResponse = CreateCommentCommentsPostResponses[keyof CreateCommentCommentsPostResponses];

export type DeleteCommentCommentsCommentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/comments/{comment_id}';
};

export type DeleteCommentCommentsCommentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCommentCommentsCommentIdDeleteError = DeleteCommentCommentsCommentIdDeleteErrors[keyof DeleteCommentCommentsCommentIdDeleteErrors];

export type DeleteCommentCommentsCommentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadCommentCommentsCommentIdGetData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/comments/{comment_id}';
};

export type ReadCommentCommentsCommentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadCommentCommentsCommentIdGetError = ReadCommentCommentsCommentIdGetErrors[keyof ReadCommentCommentsCommentIdGetErrors];

export type ReadCommentCommentsCommentIdGetResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type ReadCommentCommentsCommentIdGetResponse = ReadCommentCommentsCommentIdGetResponses[keyof ReadCommentCommentsCommentIdGetResponses];

export type ReadCommentsForPostCommentsPostPostIdGetData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/comments/post/{post_id}';
};

export type ReadCommentsForPostCommentsPostPostIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadCommentsForPostCommentsPostPostIdGetError = ReadCommentsForPostCommentsPostPostIdGetErrors[keyof ReadCommentsForPostCommentsPostPostIdGetErrors];

export type ReadCommentsForPostCommentsPostPostIdGetResponses = {
    /**
     * Response Read Comments For Post Comments Post  Post Id  Get
     *
     * Successful Response
     */
    200: Array<CommentPublic>;
};

export type ReadCommentsForPostCommentsPostPostIdGetResponse = ReadCommentsForPostCommentsPostPostIdGetResponses[keyof ReadCommentsForPostCommentsPostPostIdGetResponses];
